### PR TITLE
Added thumbs up/down buttons some other bits and bobs

### PR DESCRIPTION
**Pull request by PikaJoyce**
Added more to the reviews.
- Partially functional thumbs up/down buttons
- Allow comments check box, need to go back to add some more styling to this.
- Formatting help, styled but I intend to make this into a modal. But working on it.

### CODE REVIEW

**Comment by Doughertyg** [comment]
Hey so... the png you are using (https://steamstore-a.akamaihd.net/public/shared/images/buttons/icons_18.png?v=3).. you are changing between thumbs down and thumbs up just by adjusting the rotation? The png looks to be a png grid of multiple different images kind of like you would do for an animated png (2d games use sprite sheets in this way) so I think changing the v=3 at the end will change which in the (sprite sheet?) png are used? They even have the different colors in there for you.

**Comment by Doughertyg** [comment]
oh wait, so you use background-position -18px to change between thumbs up and thumbs down? In that case you should be able to take it even further and do background-position -##px to get the highlighted white thumb look... Need to figure out what the px size is of each img cell

**Review by Doughertyg — APPROVED** [review]
I approve your changes. Thanks for making the adjustments and let us know about the styling changes! thumbs up png background-position should now be 0px for blue thumbs up, -18px for blue thumbs down, -72px for white thumbs up, and -90px for white thumbs down! I feel like a designer now!

**Comment by PikaJoyce** [comment]
Added that submit button, and upon Graham's 500% suggestion, got the thumbs up and down to turn white. A whole bunch of things I need to fix.

- Add drop down tables
- Add those three lines by the in library tab thing.
- Allow Comments check box still needs to turn blue when checked.
- Fix up fonts (what size are you???)
- Add gradient on hover for all buttons
- Basically everything.

**Pull request merged**
